### ISSUE TITLE
code:1111 信息填写的都是对的，请问是怎么回事哇？救救饿肚子的孩子

### ISSUE THREAD

**Issue by MisakaMikoto86** [LovelyWhite/ddmc#1]
首先谢谢作者的分享！！
测试了一下，提示如下（updating cart  code:1111 msg:您的访问已过期,请重新登录app~）
请问是哪里出了问题（Configs.java都正确填写了）

**Comment by ljy1996l** [comment]
他这里的url参数不对

**Comment by haifengzuishuai** [comment]
Sign过期了吧

**Comment by LovelyWhite** [comment]
cookie 填错了估计是。

**Comment by lijyy** [comment]
真的是http请求么，貌似抓包抓到的都是https。还有就是，如果url参数错误、header有误也会报访问过期。

**Comment by LovelyWhite** [comment]
> 真的是http请求么，貌似抓包抓到的都是https。还有就是，如果url参数错误、header有误也会报访问过期。

貌似，http 与 https 都行。

**Comment by nickww520** [comment]
一脸懵逼中，我都不知道咋用，有没有大佬教一教？

**Comment by bug-correcter** [comment]
#4 还报1111代码的请参考这里
