### ISSUE TITLE
会被封号，或者限制账号吗

### ISSUE THREAD

**Issue by windherd** [LovelyWhite/ddmc#10]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by LovelyWhite** [comment]
maybe，目前还没有人反应过。

**Comment by zijianziye** [comment]
我号已被封，无限刷新购物车，在和叮咚官方联系中

**Comment by LovelyWhite** [comment]
@zijianziye 无限刷新购物车是什么意思。

**Comment by zijianziye** [comment]
> 

和官方联系了，官方说我刷新过多。。不过我改了延迟。。。

**Comment by lagunazeng** [comment]
> 

改了还被封吗？改成多少了？

**Comment by windherd** [comment]
账号已经被封禁，购物车接口返回405

**Comment by awfulsunday** [comment]
今早用其他脚本抢到一点点。上午脚本里一半的请求返回 405，现在卡在 checkOrder，全是 405 了。现在手动购物车去结算一直显示获取订单信息异常。应该是被封了

**Comment by LovelyWhite** [comment]
> 今早用其他脚本抢到一点点。上午脚本里一半的请求返回 405，现在卡在 checkOrder，全是 405 了。现在手动购物车去结算一直显示获取订单信息异常。应该是被封了

非高峰期打开购物车也是订单信息异常？

**Comment by awfulsunday** [comment]
> > 今早用其他脚本抢到一点点。上午脚本里一半的请求返回 405，现在卡在 checkOrder，全是 405 了。现在手动购物车去结算一直显示获取订单信息异常。应该是被封了
> 
> 非高峰期打开购物车也是订单信息异常？

是的，现在就是。我换了一个手机号去看是不会这样显示的。之前我设置的刷新时长是 1-3s，别的仓库有人说设置成 10s 级别

**Comment by LovelyWhite** [comment]
可能是偶然吧...我的就没封，开发都是用我自己的账号做的测试.. 应该是你触发了某种策略，暂时限流。

**Comment by awfulsunday** [comment]
> 可能是偶然吧...我的就没封，开发都是用我自己的账号做的测试..

我是用的别的脚本，两三天了，今天封的

**Comment by windherd** [comment]
不到12个小时就解封了，重新获得抢食权。

**Comment by awfulsunday** [comment]
是的，现在就是。我换了一个手机号去看是不会这样显示的。之前我设置的刷新时长是 1-3s，另一个仓库有人说设置成 10s 级别
