### ISSUE TITLE
IOS抓包 无法触发GET https://sunquan.api.ddxq.mobi/api/v1/user/address

### ISSUE THREAD

**Issue by Strider1230** [LovelyWhite/ddmc#11]
使用IOS工具Stream对叮咚买菜app进行抓包，进入购物车更换地址以后只能抓到trackercollect.ddxq.mobi，无法触发GET https://sunquan.api.ddxq.mobi/api/v1/user/address，想问问你是用的叮咚买菜小程序进行的抓包吗?还是说我的操作有误，还是说是iOS端的Stream本身无法抓取地址更换的请求包，目前这几种情况无法得证

**Comment by Strider1230** [comment]
> 使用IOS工具Stream对叮咚买菜app进行抓包，进入购物车更换地址以后只能抓到trackercollect.ddxq.mobi，无法触发GET [https://sunquan.api.ddxq.mobi/api/v1/user/address，想问问你是用的叮咚买菜小程序进行的抓包吗?还是说我的操作有误，还是说是iOS端的Stream本身无法抓取地址更换的请求包，目前这几种情况无法得证](https://sunquan.api.ddxq.mobi/api/v1/user/address%EF%BC%8C%E6%83%B3%E9%97%AE%E9%97%AE%E4%BD%A0%E6%98%AF%E7%94%A8%E7%9A%84%E5%8F%AE%E5%92%9A%E4%B9%B0%E8%8F%9C%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%BF%9B%E8%A1%8C%E7%9A%84%E6%8A%93%E5%8C%85%E5%90%97?%E8%BF%98%E6%98%AF%E8%AF%B4%E6%88%91%E7%9A%84%E6%93%8D%E4%BD%9C%E6%9C%89%E8%AF%AF%EF%BC%8C%E8%BF%98%E6%98%AF%E8%AF%B4%E6%98%AFiOS%E7%AB%AF%E7%9A%84Stream%E6%9C%AC%E8%BA%AB%E6%97%A0%E6%B3%95%E6%8A%93%E5%8F%96%E5%9C%B0%E5%9D%80%E6%9B%B4%E6%8D%A2%E7%9A%84%E8%AF%B7%E6%B1%82%E5%8C%85%EF%BC%8C%E7%9B%AE%E5%89%8D%E8%BF%99%E5%87%A0%E7%A7%8D%E6%83%85%E5%86%B5%E6%97%A0%E6%B3%95%E5%BE%97%E8%AF%81)

刚刚发现iOS端使用叮咚小程序进行地址调换可以触发

**Comment by LovelyWhite** [comment]
app 抓不了，只能用小程序，或者 给到 app
