### ISSUE TITLE
deviceToken怎么获取啊用的ios stream抓的

### ISSUE THREAD

**Issue by CcCbreeze** [LovelyWhite/ddmc#12]
deviceToken怎么获取啊用的ios stream抓的

**Comment by LovelyWhite** [comment]
不是有吗？你在仔细看看

**Comment by zijianziye** [comment]
当前购物车商品:
香葱 50g	¥0.99	 数量:1
鲜活基围虾（20-28只） 350g	¥43.90	 数量:1

已刷新购物车是否继续？(Y/N)
y

Process finished with exit code 0

请问这是什么情况？
