### ISSUE TITLE
按Y后显示Process finished with exit code 0，请问这是啥情况？

### ISSUE THREAD

**Issue by zijianziye** [LovelyWhite/ddmc#13]
当前购物车商品:
香葱 50g ¥0.99 数量:1
鲜活基围虾（20-28只） 350g ¥43.90 数量:1

已刷新购物车是否继续？(Y/N)
y

Process finished with exit code 0

请问这是什么情况？

**Comment by zijianziye** [comment]
好了 是ADDRESS输入错误

**Comment by LovelyWhite** [comment]
大写的 Y

**Comment by zijianziye** [comment]
谢了兄弟
