### ISSUE TITLE
抢购失败

### ISSUE THREAD

**Issue by zijianziye** [LovelyWhite/ddmc#14]
Range:【 2022-04-10T18:30 | 2022-04-10T22:30 】->>>code:-3000 msg:当前人多拥挤，请稍后尝试刷新页面
Range:【 2022-04-10T10:30 | 2022-04-10T14:30 】->>>code:-3000 msg:当前人多拥挤，请稍后尝试刷新页面
Range:【 2022-04-10T06:30 | 2022-04-10T10:30 】->>>code:-3000 msg:当前人多拥挤，请稍后尝试刷新页面
Range:【 2022-04-10T18:30 | 2022-04-10T22:30 】->>>code:-3000 msg:当前人多拥挤，请稍后尝试刷新页面
Range:【 2022-04-10T14:30 | 2022-04-10T18:30 】->>>code:1 msg:参数错误
Range:【 2022-04-10T10:30 | 2022-04-10T14:30 】->>>code:-3000 msg:当前人多拥挤，请稍后尝试刷新页面
Range:【 2022-04-10T06:30 | 2022-04-10T10:30 】->>>code:-3000 msg:当前人多拥挤，请稍后尝试刷新页面
Range:【 2022-04-10T18:30 | 2022-04-10T22:30 】->>>code:-3000 msg:当前人多拥挤，请稍后尝试刷新页面
Range:【 2022-04-10T10:30 | 2022-04-10T14:30 】->>>code:-3000 msg:当前人多拥挤，请稍后尝试刷新页面

不知道问题是不是出现在时间段选择，现在上海有8个时间段了

**Comment by LovelyWhite** [comment]
检查中。

**Comment by LovelyWhite** [comment]
参数错误的 log 方便发一下么？可以的话发的时候注意脱敏

**Comment by LovelyWhite** [comment]
已 fix，请重新拉取最新代码，应该是 header 里的 clientId 没改。
