### ISSUE TITLE
请问大佬怎么可以不要某个配送时间段呀

### ISSUE THREAD

**Issue by coldtea07** [LovelyWhite/ddmc#17]
社区超过八点就不给送了，想排除掉20点30到22点30这个时间，感谢！

**Comment by LovelyWhite** [comment]
https://github.com/LovelyWhite/ddmc/blob/a88671dbb58d9beca446e351862b4327f444551f/src/main/java/utils/Configs.java#L53-L56

这里每一行对应一个时间段，删除你不需要的即可。
