### ISSUE TITLE
抢到了，支付失败

### ISSUE THREAD

**Issue by zyj20200** [LovelyWhite/ddmc#19]
抓的小程序的包，订单详情里面支付方式是关爱通，支付提示“抱歉，同一时间下单人数过多，建议您稍后再试”
![](https://s3.bmp.ovh/imgs/2022/04/11/330a0db9bc509f1c.png)

**Comment by zyj20200** [comment]
配置文件：
```
public static final String stationId = "5b98842xxxxxxxxxxxxxxxx";
public static final String addressId = "5ff5c09xxxxxx";
public static final String cityNumber = "0101";
public static final Double latitude = 31.xxx;
public static final Double longitude = 121.xxx;
public static final String appClientId = "4"; // 小程序请设置为 4

public static final String cookie = "DDXQSESSID=xxxxxxxxxxxxxxxxxx";
public static final String uid = "5ff5xxxxxxxxxxxxxxxxxxx";
public static final String deviceToken = "WHJMrxxxxxxxxxxxxx";

/**
 * 注意，小程序的 api 版本与给到不同
 * 给到: apiVersion 9.44.0、 appVersion 2.74.2
 * 小程序: apiVersion 9.49.2、 appVersion 2.82.0
 */
public static final String apiVersion = "9.49.2";
public static final String appVersion = "2.82.0";
```

**Comment by coldtea07** [comment]
8点半那波我也是这个样子。。。。昨天好像也是 6点那波没问题

**Comment by nickww520** [comment]
> 抓的小程序的包，订单详情里面支付方式是关爱通，支付提示“抱歉，同一时间下单人数过多，建议您稍后再试” ![](https://camo.githubusercontent.com/9a0daaf67304814388456267c3624c689d9891da89547263202e433687748274/68747470733a2f2f73332e626d702e6f76682f696d67732f323032322f30342f31312f333330613064623962633530396631632e706e67)

老哥能教教这个脚本用idea怎么使用不？ 或者来个使用教程地址也可以，感谢！

**Comment by LovelyWhite** [comment]
@zyj20200 刚试了一下，我这边未复现呢，你确定配置正确吗？
<img src="https://user-images.githubusercontent.com/23720995/162650729-f83be86a-415d-4e47-8385-f17b112a4b16.png" width=350 />

**Comment by coldtea07** [comment]
@LovelyWhite  大佬，我也是这样，我同样的配置抢了2单，一单是小程序付款，一单是关爱通，两次配置都没变得。

**Comment by zyj20200** [comment]
@LovelyWhite 配置贴上面了，应该没错吧，要修改的地方都改了。

**Comment by nickww520** [comment]
> @zyj20200 刚试了一下，我这边未复现呢，你确定配置正确吗？ <img alt="" width="350" src="https://user-images.githubusercontent.com/23720995/162650729-f83be86a-415d-4e47-8385-f17b112a4b16.png">

大佬，能不能教教我怎么使用啊，救救没饭吃的孩子吧，救命啊！

**Comment by zyj20200** [comment]
> > @zyj20200 刚试了一下，我这边未复现呢，你确定配置正确吗？ <img alt="" width="350" src="https://user-images.githubusercontent.com/23720995/162650729-f83be86a-415d-4e47-8385-f17b112a4b16.png">
> 
> 大佬，能不能教教我怎么使用啊，救救没饭吃的孩子吧，救命啊！

idea打开项目文件夹，找到Entry文件，右击Run

**Comment by LovelyWhite** [comment]
fixed
