### ISSUE TITLE
现在时间段很诡异不是正好的间隔2或者4小时那PERIODS那段代码手动怎么改

### ISSUE THREAD

**Issue by zorroforever** [LovelyWhite/ddmc#20]
如题 
比如
现在时间是7：15分，
点开小程序的送达时间
有2个时间段
07：17-14：30
14：30-19：00
那PERIODS那段代码手动怎么改吖？
或者说能不能通过接口获取正确的时间段，求教大大

**Comment by LovelyWhite** [comment]
目前暂不支持通过接口获取时间，目的是尽量减少接口的调用。
代码层面会将当前时间重写到时间段内，并舍去不可用时间段 。

https://github.com/LovelyWhite/ddmc/blob/a88671dbb58d9beca446e351862b4327f444551f/src/main/java/utils/Requests.java#L35-L48

eg: 当前时间 7:15
- 时间段配置:
  - 6:30 - 14:30
  - 14:30 - 22:30
- 实际请求的时间段：
  - 7:15+5min = 7:20 - 14:30
  - 14:30 - 22:30


eg: 当前时间 13:50
- 时间段配置:
  - 6:30 - 14:30
  - 14:30 - 22:30
- 实际请求的时间段：
  - 14:30 - 22:30
 
 **issue 的答案：**

1. 19:00 sub(-) 14:30 = 4.5 小时 => 时间间隔为 4.5 小时 TIME_INTERVAL =  4 * 60 * 60 + 30 * 60
1. 14:30 sub(-) 4.5 小时 => 推算出开始时间  BEGIN =  10 * 60 * 60

因为有两个时间段所以: PERIODS:

```java
  TODAY_ZERO.plusSeconds(BEGIN),
  TODAY_ZERO.plusSeconds(BEGIN + TIME_INTERVAL)
```

**Comment by zorroforever** [comment]
谢谢大大的回复，明白这段代码逻辑啦。
早上我取时间段的时候，拿到个好像叫自动还是动态时间的字眼，这个是新的时间段？这种怎么设置timerange吖

**Comment by LovelyWhite** [comment]
@zorroforever 这种测试一下就知道了，其实是一样的，应该是前端做的随机选取。

**Comment by zorroforever** [comment]
> 

好哒，我明白啦。谢谢大大回复呢，那我把问题关啦
