### ISSUE TITLE
如果是会员第一次下单，达不到免运费的金额，会员减免运费5元

### ISSUE THREAD

**Issue by AugustT2** [LovelyWhite/ddmc#21]
payment_order.setFreight_discount_money("0.00");
这一行的值不是0了，是5。
https://github.com/LovelyWhite/ddmc/blob/main/src/main/java/model/order/PackageOrder.java#L107

**Comment by LovelyWhite** [comment]
特殊情况暂时不做支持哈～，有需要的可以自行修改一下。
