### ISSUE TITLE
大佬求助2天了都是AssertError 405

### ISSUE THREAD

**Issue by zorroforever** [LovelyWhite/ddmc#29]
在拉取购物车的时候，一直405走到
if (result.contains("AssertError")) {
            result = "{\"msg\":\"AssertError\",\"code\":405,\"data\":null,\"isSuccess\":false}";
        }
这个逻辑。

我手动在app或者小程序上点购物车也是打不开了
小程序抓包也是assererror 405错误
是不是账号被封了吖？
大佬求助

**Comment by LovelyWhite** [comment]
是的

**Comment by zorroforever** [comment]
好哒 我后面找他们客服 客服给我解封了。哈哈 谢谢大佬
