### ISSUE TITLE
访问过期1111报错已经解决，参数变了，严格按以下格式核对参数，没有就加

### ISSUE THREAD

**Issue by bug-correcter** [LovelyWhite/ddmc#4]
`https://maicai.api.ddxq.mobi/cart/index?
uid=
&longitude=
&latitude=
&station_id=
&city_number=
&api_version=
&app_version=
&applet_source=
&channel=
&app_client_id=
&sharer_uid=
&s_id=
&openid=
&h5_source=
&device_token=
&is_load=
&ab_config=
&nars=
&sesi=`
ios直接抓app抓不到了，建议抓微信小程序，但是现在有新问题，购物车一直显示为空
![image](https://user-images.githubusercontent.com/23416089/162561518-885cfe2f-6310-4c43-bead-988f97eba466.png)

**Comment by nickww520** [comment]
> `https://maicai.api.ddxq.mobi/cart/index? uid= &longitude= &latitude= &station_id= &city_number= &api_version= &app_version= &applet_source= &channel= &app_client_id= &sharer_uid= &s_id= &openid= &h5_source= &device_token= &is_load= &ab_config= &nars= &sesi=` ios直接抓app抓不到了，建议抓微信小程序，但是现在有新问题，购物车一直显示为空 ![image](https://user-images.githubusercontent.com/23416089/162561518-885cfe2f-6310-4c43-bead-988f97eba466.png)

大佬，这个脚本用什么软件运行啊？

**Comment by bug-correcter** [comment]
> 

IDEA

**Comment by bug-correcter** [comment]
config的addressid不能随便填吧，这里不识别
![image](https://user-images.githubusercontent.com/23416089/162562958-66d86a4e-361d-4fd0-99d4-5fff6460670d.png)

**Comment by nickww520** [comment]
> > 
> 
> IDEA

这个我下载安装了，提示让我买通行证才给用，有没有免费的下载地址啊？

**Comment by bug-correcter** [comment]
> > > 
> > 
> > 
> > IDEA
> 
> 这个我下载安装了，提示让我买通行证才给用，有没有免费的下载地址啊？

百度搜激活方式，按教程来就行，这个仓库的代码我运行到提交订单就寄了，小白不建议继续深入研究，难度较大

**Comment by youlv123** [comment]
addressid哪里去找？

**Comment by LovelyWhite** [comment]
> addressid哪里去找？

文档更新了，找 api/v1/user/address 的返回值

**Comment by LovelyWhite** [comment]
> > > 
> > 
> > 
> > IDEA
> 
> 这个我下载安装了，提示让我买通行证才给用，有没有免费的下载地址啊？

可以下载社区版，是免费的  [link](https://www.jetbrains.com/idea/download/download-thanks.html?platform=windows&code=IIC)

**Comment by nickww520** [comment]
> > > > 
> > > 
> > > 
> > > IDEA
> > 
> > 
> > 这个我下载安装了，提示让我买通行证才给用，有没有免费的下载地址啊？
> 
> 可以下载社区版，是免费的 [link](https://www.jetbrains.com/idea/download/download-thanks.html?platform=windows&code=IIC)

多谢指点，你抢菜搞定了不？我用strem抓的包，addressid 就这个id 没有找到了 其他都找都了

**Comment by nickww520** [comment]
> > > > 
> > > 
> > > 
> > > IDEA
> > 
> > 
> > 这个我下载安装了，提示让我买通行证才给用，有没有免费的下载地址啊？
> 
> 可以下载社区版，是免费的 [link](https://www.jetbrains.com/idea/download/download-thanks.html?platform=windows&code=IIC)

再个问题，返回值在strem抓包之后哪里找啊？ 我在data包里找不到 addressid

**Comment by LovelyWhite** [comment]
https://github.com/LovelyWhite/ddmc/issues/4#issuecomment-1093877855 看这个。
找 `https://sunquan.api.ddxq.mobi/api/v1/user/address` 请求的响应值，valid_address 里的 id 字段。
